name: BiOSGen
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
      - moondream==0.0.5
      - opencv-python
      - torch 
      - torchvision 
      - numpy 
      - pandas
      - matplotlib
      - seaborn 
      - scikit-image
      - requests
      - scikit-learn 
      - pyyaml 
      - tqdm 
      - transformers
      - einops
      - pyvips
      - git+https://github.com/openai/CLIP.git
      - diffusers
      - transformers
      - accelerate
      - loralib
      - peft
      - thop
      - omegaconf

  - conda:
    - libvips
    - glib