device: 'cpu'

batch_size: 3
learning_rate: 1e-4
num_epochs: 100
gradient_clip_val: 1.0

losses:
  lambda_content: 1e-3
  lambda_style: 1e-5
  lambda_structure: 1e-4
  lambda_ca: 1e-4
  
optimizer:      # Adam as default
  lr: 1e-4
  weight_decay: 1e-6
  
# Image parameters
Image:
  default_size: 256
  default_channels: 3

  tissue_mask_params: 
    kernel_size: 20
    sigma: 20
    downsample: 8
    background_gray_threshold: 220

  patch_extraction_params:
    patch_size: 256
    patch_tissue_threshold: 0.7
    is_visualize: False